services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ./data:/app/api/data
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8282:8282"
    depends_on:
      - api

